### ISSUE TITLE
installation issue in google colab

### ISSUE THREAD

**Issue by FahimHafiz** [rui-yan/TabMap#1]
Hello, kudos to your Fascinating work! I am trying to run the "Tutorial_Feature_Importance.ipynb"  file where I initially installed the tabmap using "pip install tabmap". However, facing the importing issues for the tabmap as shown in the attached image. Can you please tell me how to resolve it?
![image](https://github.com/user-attachments/assets/4d3ffeb0-bac5-4a42-90e0-2b8b72f7b1ff)

**Comment by rui-yan** [comment]
Thank you for pointing this out. We have updated the package. Please run `pip install tabmap==0.1.2` to download the latest version and try again.

**Comment by FahimHafiz** [comment]
Thanks a lot for your quick response! It's working now.
